/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-12-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class FootballAssociationHandler {

    public static Football_Association__c getFootballAssociationObject(String footballAssociationLink) {
        Football_Association__c footballAssociation = new Football_Association__c();

        return footballAssociation;
    }
}