web:
  build: .
  command: 'bash -c ''node app.js'''
  working_dir: /usr/src/app
  environment:
    PORT: 8050
    NGINX_PORT: 8443
  volumes:
    - './views:/app/user/views:ro'
nginx:
  build: nginx
  ports:
    - '8080:80'
    - '8443:443'
  links:
    - web:web
  volumes_from:
    - web
