/**
 * @description       : Use the with sharing keyword when declaring a class to enforce sharing rules of the current user. 
 * @author            : Flávio Ferreira
 * @group             : 
 * @last modified on  : 12-03-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 *
 * Source:
 * https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_keywords_sharing.htm
**/
public with sharing class SharingClass {

    // Code here
 
 }