/**
 * @description       : An if statement is a true-false test that enables your application to do different things based on a condition.
 * @author            : Flávio Ferreira
 * @group             : 
 * @last modified on  : 11-21-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class Branching {

    public static void runIfStatement() {
        Boolean condition = true;
        if (condition) {
            // Do this if the condition is true
        } else {
            // Do this if the condition is not true
        }
    }
}